"""Initial migration

Revision ID: 7a38404fc5c7
Revises: 
Create Date: 2025-07-22 14:18:56.746089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a38404fc5c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('chat_history')
    op.drop_table('sessions')
    op.drop_table('analysis_results')
    op.drop_table('tracks')
    op.drop_table('reference_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.VARCHAR(), nullable=False),
    sa.Column('subgenre', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('analysis_json', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('track_name', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.VARCHAR(), nullable=True),
    sa.Column('peak_db', sa.FLOAT(), nullable=True),
    sa.Column('rms_db_avg', sa.FLOAT(), nullable=True),
    sa.Column('rms_db_peak', sa.FLOAT(), nullable=True),
    sa.Column('lufs', sa.FLOAT(), nullable=True),
    sa.Column('dynamic_range', sa.FLOAT(), nullable=True),
    sa.Column('stereo_width_ratio', sa.FLOAT(), nullable=True),
    sa.Column('stereo_width', sa.VARCHAR(), nullable=True),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('tempo', sa.FLOAT(), nullable=True),
    sa.Column('low_end_energy_ratio', sa.FLOAT(), nullable=True),
    sa.Column('low_end_description', sa.VARCHAR(), nullable=True),
    sa.Column('band_energies', sa.VARCHAR(), nullable=True),
    sa.Column('spectral_balance_description', sa.VARCHAR(), nullable=True),
    sa.Column('issues', sa.TEXT(), nullable=True),
    sa.Column('peak_issue', sa.TEXT(), nullable=True),
    sa.Column('peak_issue_explanation', sa.TEXT(), nullable=True),
    sa.Column('avg_transient_strength', sa.FLOAT(), nullable=True),
    sa.Column('max_transient_strength', sa.FLOAT(), nullable=True),
    sa.Column('transient_description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('session_name', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('track_id', sa.VARCHAR(), nullable=True),
    sa.Column('sender', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('feedback_profile', sa.VARCHAR(), nullable=True),
    sa.Column('followup_group', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
